#!/usr/bin/env bats
# Contract tests — the shared docs must define the trigger/class/TSV/rules formats.

load '../test_helper'

TEMPLATES="$ROOT/skills/_shared/workspace-templates.md"
CORE="$ROOT/skills/_shared/workspace-core.md"

@test "templates: document the triggers frontmatter block" {
  run grep -c 'triggers:' "$TEMPLATES"
  assert_success
}

@test "templates: triggers block lists paths, commands, keywords" {
  run grep -E '^  (paths|commands|keywords):' "$TEMPLATES"
  assert_success
  assert_line --partial "paths:"
  assert_line --partial "commands:"
  assert_line --partial "keywords:"
}

@test "templates: document the class marker with all four values" {
  run grep -E 'class:.*correction.*directive.*pattern.*preference' "$TEMPLATES"
  assert_success
}

@test "templates: document the triggers.tsv column format" {
  run grep -F 'triggers.tsv' "$TEMPLATES"
  assert_success
  run grep -E 'kind.*path\|command\|keyword' "$TEMPLATES"
  assert_success
}

@test "templates: document the generated rules path and header" {
  run grep -F '.claude/rules/hydra/' "$TEMPLATES"
  assert_success
  run grep -F 'GENERATED BY hydra-claude' "$TEMPLATES"
  assert_success
}

@test "core: layout table includes triggers.tsv and archive exclusion note" {
  run grep -F 'triggers.tsv' "$CORE"
  assert_success
}
