#!/usr/bin/env bats
# Contract tests — the shared docs must define the trigger/class/TSV/rules formats.

load '../test_helper'

TEMPLATES="$ROOT/skills/_shared/workspace-templates.md"
CORE="$ROOT/skills/_shared/workspace-core.md"

@test "templates: document the triggers frontmatter block" {
  run grep -c 'triggers:' "$TEMPLATES"
  assert_success
}

@test "templates: triggers block lists paths, commands, keywords" {
  run grep -E '^  (paths|commands|keywords):' "$TEMPLATES"
  assert_success
  assert_line --partial "paths:"
  assert_line --partial "commands:"
  assert_line --partial "keywords:"
}

@test "templates: document the class marker with all four values" {
  run grep -E 'class:.*correction.*directive.*pattern.*preference' "$TEMPLATES"
  assert_success
}

@test "templates: document the triggers.tsv column format" {
  run grep -F 'triggers.tsv' "$TEMPLATES"
  assert_success
  run grep -E 'kind.*path\|command\|keyword' "$TEMPLATES"
  assert_success
}

@test "templates: document the generated rules path and header" {
  run grep -F '.claude/rules/hydra/' "$TEMPLATES"
  assert_success
  run grep -F 'GENERATED BY hydra-claude' "$TEMPLATES"
  assert_success
}

@test "core: layout table includes triggers.tsv and archive exclusion note" {
  run grep -F 'triggers.tsv' "$CORE"
  assert_success
}

LEARN="$ROOT/skills/learn/SKILL.md"
SEED="$ROOT/skills/seed-memory/SKILL.md"

@test "learn: instructs populating triggers at write time" {
  run grep -c 'triggers:' "$LEARN"
  assert_success
  run grep -F 'never invent triggers broader' "$LEARN"
  assert_success
}

@test "learn: instructs assigning entry class from capture trigger" {
  run grep -E 'class:.*correction' "$LEARN"
  assert_success
}

@test "learn: instructs running the index builder after writes" {
  run grep -F 'build-triggers-index.sh' "$LEARN"
  assert_success
}

@test "learn: instructs running the rules compiler after writes" {
  run grep -F 'compile-rules.sh' "$LEARN"
  assert_success
}

@test "learn: extends legacy upgrade to backfill triggers" {
  run grep -iE 'legacy.*triggers|triggers.*legacy' "$LEARN"
  assert_success
}

@test "seed-memory: instructs triggers population and both scripts" {
  run grep -F 'build-triggers-index.sh' "$SEED"
  assert_success
  run grep -F 'compile-rules.sh' "$SEED"
  assert_success
  run grep -c 'triggers:' "$SEED"
  assert_success
}

@test "seed-memory: seeded entries never get correction/directive class" {
  run grep -iE 'never.*(correction|directive)|(correction|directive).*never' "$SEED"
  assert_success
  run grep -F 'class: pattern' "$SEED"
  assert_success
}

RULES_MD="$ROOT/CLAUDE.md"

@test "CLAUDE.md: has check-before-acting recall protocol" {
  run grep -iE 'check before acting|recall protocol' "$RULES_MD"
  assert_success
}

@test "CLAUDE.md: requires announcing every applied memory" {
  run grep -F 'Applying saved pattern' "$RULES_MD"
  assert_success
}

@test "CLAUDE.md: requires memory context in subagent prompts" {
  run grep -iE 'subagent.*(memory|entries)' "$RULES_MD"
  assert_success
}
