#!/usr/bin/env bash
# Compiles topic files with triggers.paths into native Claude Code path-scoped
# rules at <rules-dir>/hydra/<topic>.md. Regenerates the whole hydra/ dir.
# Usage: compile-rules.sh <memory-dir> <rules-dir>
set -u

MEM_DIR="${1:-}"
RULES_DIR="${2:-}"
[ -n "$MEM_DIR" ] && [ -d "$MEM_DIR" ] && [ -n "$RULES_DIR" ] || exit 0

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/../hooks/_recall-lib.sh"

HYDRA_RULES="$RULES_DIR/hydra"
mkdir -p "$HYDRA_RULES"
rm -f "$HYDRA_RULES"/*.md 2>/dev/null

for f in "$MEM_DIR"/*.md; do
  [ -f "$f" ] || continue
  base=$(basename "$f")
  [ "$base" = "MEMORY.md" ] && continue

  paths=$(awk '
    NR == 1 && !/^---[[:space:]]*$/ { exit }
    NR == 1                          { next }
    /^---[[:space:]]*$/              { exit }
    /^triggers:/                     { in_triggers = 1; next }
    in_triggers && /^[a-zA-Z_]/      { in_triggers = 0 }
    in_triggers && /^  paths:/       { kind = "path"; next }
    in_triggers && /^  (commands|keywords):/ { kind = ""; next }
    in_triggers && kind == "path" && /^    - / {
      pat = $0; sub(/^    - /, "", pat); gsub(/^"|"$/, "", pat)
      if (pat != "") print pat
    }
  ' "$f")
  [ -n "$paths" ] || continue

  entries=$(extract_entries "$f")
  entry_lines=$(printf '%s\n' "$entries" | wc -l | tr -d ' ')
  if [ "$entry_lines" -gt 100 ]; then
    entries=$(extract_entries_by_class "$f" "correction|directive")
    entries="$entries
See the full topic file: .claude/memory/plugin/$base"
  fi

  {
    echo '---'
    echo 'paths:'
    printf '%s\n' "$paths" | while IFS= read -r p; do
      printf '  - "%s"\n' "$p"
    done
    echo '---'
    echo "<!-- GENERATED BY hydra-claude from .claude/memory/plugin/$base — edit that file, not this one. -->"
    echo
    printf '%s\n' "$entries"
  } > "$HYDRA_RULES/$base"
done

exit 0
