#!/usr/bin/env bats
# Tests for scripts/compile-rules.sh

load '../test_helper'

COMPILER="$ROOT/scripts/compile-rules.sh"

setup() {
  MEM_DIR="$BATS_TEST_TMPDIR/mem"
  RULES_DIR="$BATS_TEST_TMPDIR/rules"
  mkdir -p "$MEM_DIR"
  cat > "$MEM_DIR/patterns-hooks.md" <<'EOF'
---
scope: "Hook conventions."
triggers:
  paths:
    - "hooks/*.sh"
  keywords:
    - "hook"
---

## Hooks must fail open
class: correction

Body.

**Why:** because.

---
EOF
}

@test "compiler: missing args exits 0" {
  run bash "$COMPILER"
  assert_success
}

@test "compiler: emits a rule with paths frontmatter and generated header" {
  run bash "$COMPILER" "$MEM_DIR" "$RULES_DIR"
  assert_success
  [ -f "$RULES_DIR/hydra/patterns-hooks.md" ]
  run cat "$RULES_DIR/hydra/patterns-hooks.md"
  assert_line 'paths:'
  assert_line '  - "hooks/*.sh"'
  assert_line --partial 'GENERATED BY hydra-claude'
  assert_line --partial '## Hooks must fail open'
}

@test "compiler: topic without path triggers produces no rule" {
  cat > "$MEM_DIR/no-paths.md" <<'EOF'
---
scope: "x"
triggers:
  keywords:
    - "y"
---

## E

B.

---
EOF
  run bash "$COMPILER" "$MEM_DIR" "$RULES_DIR"
  [ ! -f "$RULES_DIR/hydra/no-paths.md" ]
}

@test "compiler: removes stale rule when topic loses its path triggers" {
  bash "$COMPILER" "$MEM_DIR" "$RULES_DIR"
  [ -f "$RULES_DIR/hydra/patterns-hooks.md" ]
  # Rewrite the topic without path triggers (full rewrite — no fragile sed ranges).
  cat > "$MEM_DIR/patterns-hooks.md" <<'EOF'
---
scope: "Hook conventions."
triggers:
  keywords:
    - "hook"
---

## Hooks must fail open
class: correction

Body.

**Why:** because.

---
EOF
  run bash "$COMPILER" "$MEM_DIR" "$RULES_DIR"
  assert_success
  [ ! -f "$RULES_DIR/hydra/patterns-hooks.md" ]
}

@test "compiler: skips MEMORY.md and archive" {
  printf -- '- [x](x.md) — y\n' > "$MEM_DIR/MEMORY.md"
  mkdir -p "$MEM_DIR/archive"
  cp "$MEM_DIR/patterns-hooks.md" "$MEM_DIR/archive/old.md"
  run bash "$COMPILER" "$MEM_DIR" "$RULES_DIR"
  [ ! -f "$RULES_DIR/hydra/MEMORY.md" ]
  [ ! -f "$RULES_DIR/hydra/old.md" ]
}

@test "compiler: over-budget topic compiles only correction/directive + pointer" {
  {
    printf -- '---\nscope: "big"\ntriggers:\n  paths:\n    - "src/*.ts"\n---\n\n'
    printf '## Critical rule\nclass: correction\n\nKeep.\n\n---\n\n'
    for i in $(seq 1 30); do printf '## Filler %s\n\nline a\nline b\nline c\n\n---\n\n' "$i"; done
  } > "$MEM_DIR/big.md"
  run bash "$COMPILER" "$MEM_DIR" "$RULES_DIR"
  run cat "$RULES_DIR/hydra/big.md"
  assert_line --partial '## Critical rule'
  refute_line --partial '## Filler 5'
  assert_line --partial 'full topic file'
}
